#!/bin/bash

doit_adsbfi(){

# TOTAL tracked aircrafts
  
  ADSBFI_TOTAL_JSON=$(jq '{state: (.aircraft_count_by_type.adsb_icao + .aircraft_count_by_type.mode_s + .aircraft_count_by_type.mlat) ,
                     attributes: {"friendly_name": "Adsb.fi Status",
                                  "icon": "mdi:airplane",
                                  "state_class": "measurement",
                                  "unit_of_measurement": "aircraft",
                                  "unique_id": "adsbfi_total"} }' \
                     /run/adsbfi-feed/status.json )
  
  curl -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" -H "Content-Type: application/json" \
    -d "$ADSBFI_TOTAL_JSON" http://supervisor/core/api/states/sensor.adsbfi_status
  
# ADS-B tracked aircrafts
  
  ADSBFI_ICAO_JSON=$(jq '{state: .aircraft_count_by_type.adsb_icao ,
                    attributes: {"friendly_name": "Adsb.fi ADS-B",
                                 "icon": "mdi:airplane",
                                 "state_class": "measurement",
                                 "unit_of_measurement": "aircraft",
                                 "unique_id": "adsbfi_adsb"} }' \
                    /run/adsbfi-feed/status.json )
  
  curl -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" -H "Content-Type: application/json"\
    -d "$ADSBFI_ICAO_JSON" http://supervisor/core/api/states/sensor.adsbfi_adsb
  
# MODE-S tracked aircrafts
  
  ADSBFI_MODES_JSON=$(jq '{state: .aircraft_count_by_type.mode_s ,
                     attributes: {"friendly_name": "Adsb.fi Mode-S",
                                  "icon": "mdi:airplane",
                                  "state_class": "measurement",
                                  "unit_of_measurement": "aircraft",
                                  "unique_id": "adsbfi_mode_s"} }' \
                     /run/adsbfi-feed/status.json )
  
  curl -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" -H "Content-Type: application/json"\
    -d "$ADSBFI_MODES_JSON" http://supervisor/core/api/states/sensor.adsbfi_mode_s
  
# MLAT tracked aircrafts
  
  ADSBFI_MLAT_JSON=$(jq '{state: .aircraft_count_by_type.mlat ,
                    attributes: {"friendly_name": "Adsb.fi MLAT",
                                 "icon": "mdi:airplane",
                                 "state_class": "measurement",
                                 "unit_of_measurement": "aircraft",
                                 "unique_id": "adsbfi_mlat"} }' \
                    /run/adsbfi-feed/status.json )
  
  curl -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" -H "Content-Type: application/json"\
    -d "$ADSBFI_MLAT_JSON" http://supervisor/core/api/states/sensor.adsbfi_mlat

# TOTAL tracks since connected

  ADSBFI_TRACKS_JSON=$(jq '{state: .total.tracks.all ,
                    attributes: {"friendly_name": "Adsb.fi Tracks",
                                 "icon": "mdi:airplane",
                                 "state_class": "measurement",
                                 "unit_of_measurement": "track",
                                 "unique_id": "adsbfi_tracks"} }' \
                    /run/adsbfi-feed/stats.json )
  
  curl -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" -H "Content-Type: application/json"\
    -d "$ADSBFI_TRACKS_JSON" http://supervisor/core/api/states/sensor.adsbfi_tracks_all

# UPTIME

  ADSBFI_UPTIME_S=$(jq '.uptime' /run/adsbfi-feed/status.json)

  ADSBFI_UPTIME=$(python3 /usr/local/share/adsbfi/convert_uptime.py "$ADSBFI_UPTIME_S")

  ADSBFI_UPTIME_JSON='{"state":'
  ADSBFI_UPTIME_JSON+="\"$ADSBFI_UPTIME\""
  ADSBFI_UPTIME_JSON+=',"attributes":'
  ADSBFI_UPTIME_JSON+='{"friendly_name":"Adsb.fi Uptime","icon":"mdi:timer","unique_id":"adsbfi_uptime"}}'

  curl -s -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" -H "Content-Type: application/json" \
    -d "$ADSBFI_UPTIME_JSON" http://supervisor/core/api/states/sensor.adsbfi_uptime
}

echo "Starting Adsb.fi hassio sensors api"

while sleep 30; do
  doit_adsbfi;
done
