#!/command/with-contenv bash

if [ "$SERVICE_ENABLE_OPENSKY" != "false" ]; then
    set -eo pipefail

    /usr/local/share/opensky/hassio-sensors 2>&1 | mawk -W interactive '{printf "%c[35m[opensky-hassio]%c[0m %s\n", 27, 27, $0}'
    # awk -W interactive ...  (prefix log messages with color and "[opensky-hassio]")
else
    tail -f /dev/null
fi
