#!/command/with-contenv bash
source /export-env-from-config.sh

if [ "$SERVICE_ENABLE_FR24FEED" != "false" ]; then
    set -eo pipefail

    /usr/local/share/flightradar/hassio-sensors 2>&1 | mawk -W interactive '{printf "%c[35m[flightradar-hassio]%c[0m %s\n", 27, 27, $0}'
    # awk -W interactive ...  (prefix log messages with color and "[flightradar-hassio]")
else
    tail -f /dev/null
fi
